import { Inter } from 'next/font/google'
import './globals.css'
import SparklesIcon from "../components/sparkle";
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={inter.className}>
            <body className="bg-gradient-to-b from-blue-900 to-cyan-600 min-h-screen">
                <main className="p-4 max-w-6xl mx-auto">
                    <header className="flex justify-between my-8">
                        <Link href="/" className="flex gap-1 text-2xl">

                            <SparklesIcon />

                            Translate-Transcribe
                        </Link>

                        <div className="justify-between flex gap-4 text-xl">

                            <nav className="flex gap-6 text-white/80">
                                <Link href="/">Home</Link>
                                <Link href="/pricing">Pricing</Link>
                                <Link href="/contact">Contact</Link>

                            </nav>

                            <p>|</p>

                            <nav className="flex gap-6 text-white/80">
                                <Link href="/logIn">Log In</Link>
                                <Link href="/signUp">Sign Up</Link>

                            </nav>

                        </div>

                    </header>
                    {children}
                </main>
            </body>
        </html>
    )
}
